# Generated by Django 4.1.2 on 2022-10-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproducts',
            name='products_image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='mainproducts',
            name='products_video',
            field=models.FileField(blank=True, upload_to='images/%y'),
        ),
    ]
